### ISSUE TITLE
Circular Bean reference with Spring Boot version 2.6.4 and LoggingInterceptor Configurations

### ISSUE THREAD

**Issue by marzelwidmer** [smcvb/gamerental#3]
Is there any issues maybe with the Axon Version `4.5.11` and the Spring Boot Version `2.6.4` ?

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  applicationConfig
└──<-──┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

The Application starts without the following Configurations in the ApplicationConfig

```

    @Autowired
    fun configureLoggingInterceptorFor(
        commandBus: CommandBus,
        loggingInterceptor: LoggingInterceptor<Message<*>?>
    ) {
        commandBus.registerDispatchInterceptor(loggingInterceptor)
        commandBus.registerHandlerInterceptor(loggingInterceptor)
    }

    @Autowired
    fun configureLoggingInterceptorFor(eventBus: EventBus, loggingInterceptor: LoggingInterceptor<Message<*>?>?) {
        eventBus.registerDispatchInterceptor(loggingInterceptor)
    }

    @Autowired
    fun configureLoggingInterceptorFor(eventProcessingConfigurer: EventProcessingConfigurer, loggingInterceptor: LoggingInterceptor<Message<*>?>?) {
        eventProcessingConfigurer.registerDefaultHandlerInterceptor { config: org.axonframework.config.Configuration?, processorName: String? -> loggingInterceptor }
    }

    @Autowired
    fun configureLoggingInterceptorFor(queryBus: QueryBus, loggingInterceptor: LoggingInterceptor<Message<*>?>) {
        queryBus.registerDispatchInterceptor(loggingInterceptor)
        queryBus.registerHandlerInterceptor(loggingInterceptor)
    }

```

**Comment by smcvb** [comment]
Well, in all honesty, you're taking a sample build on an older version of Spring Boot that fails with a newer version. 
Not completely the sample's fault, of course ;-)

Nonetheless, it's a known one to me.
Spring Boot has enforced a certain approach they had around circular dependencies between `@Bean` and `@Autowired` methods.
To resolve this within an Axon Framework application, you can roughly do two things:

1. Introduce a `ConfigurerModule` bean that performs the configuration, solving the issue by configuring with Axon's lifecycles instead of Spring's.
2. Move the auto-wired methods to different configuration classes to separate the operations, effectively solving the circular dependency within a config class.

I have done both options 1 and 2, for the `LoggingInterceptor` configuration on the buses and for the result interceptor configuration on the reactor gateways respectively.
All this has been pushed, so I feel confident your problems will be solved by checking out what `master` looks like right now, @marzelwidmer.
