### ISSUE TITLE
H2 console not viewable unless spring mvc is added as dependency 

### ISSUE THREAD

**Issue by vab2048** [smcvb/gamerental#4]
Hey Steven,

Currently when I run the program and try to access the H2 console: localhost:8080/h2-console I get a 404 even though you have enabled it in the properties.

Apparently the H2 console is not autoconfigured by default when only using webflux so adding the spring mvc dependency resolved the problem and I can now see the console and connect using the string (jdbc:h2:./database;AUTO_SERVER=TRUE).

Just letting you know - I think you should either add the dependency: 

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
```

Or if you were connecting to the H2 database another way maybe add something to the README to describe it?

Regards,

**Comment by smcvb** [comment]
Thanks for the suggestion, @vab2048.
I always use the integrated Database interface of IntelliJ IDEA to tap into the database-of-choice for a given (sample) project.
However, not everybody uses IntelliJ IDEA, of course.

I've added the `spring-boot-starter-web` dependency in commit 75237a82b442ea8f90cdc78b8a7251d4abc523af, so that you can check out the database at `localhost:8080/h2-console`.
With that, I think I can close your issue. Just let me know if anything's amiss!
